### ISSUE TITLE
Android Demo does not work

### ISSUE THREAD

**Issue by swaytz** [sqlite-sync/SQLite-sync.com#29]
The application could not be installed: INSTALL_FAILED_NO_MATCHING_ABIS
Installation failed due to: 'null'

For the later sdk versions of 27 or higher

**Comment by swaytz** [comment]
This is solved. The error was triggered due to a mismatch of the apache commons version. On change to version 2.5, the installation was successful.

**Comment by linking123** [comment]
THX..

I meet the same problem. And i update `implementation 'org.apache.directory.studio:org.apache.commons.io:2.4'` to `implementation group: 'commons-io', name: 'commons-io', version: '2.7'` and then run success.
