### ISSUE TITLE
API[3.2.15] SQLite-Sync.COM is working correctly! Error creating database connection.

### ISSUE THREAD

**Issue by luiza-avelino** [sqlite-sync/SQLite-sync.com#33]
I'm receiving this error when access: localhost:8080/sync/API3.

My web.xml:
<env-entry>
        <env-entry-name>working-dir</env-entry-name>
        <env-entry-type>java.lang.String</env-entry-type>
        <env-entry-value>C:\Users\Luiza\sync\</env-entry-value>
    </env-entry>

My sync.properties file(located at 'C:\Users\Luiza\sync\config\sync.properties') :

DB_ENGINE = postgres
DBURL = jdbc:postgresql://localhost:56582/sync
DBUSER = postgres
DBPASS = postgres
DBDRIVER = org.postgresql.Driver
DATE_FORMAT = yyyy-MM-dd HH:mm:ss
HISTORY_DAYS = 7
LOG_LEVEL = 4

**Comment by IchoTolot** [comment]
Hi,
can you connect to the database with this credentials and pgAdmin?

**Comment by luiza-avelino** [comment]
Yes,

credentials is OK, dbname is OK. I really don't know what's the problem

**Comment by IchoTolot** [comment]
Please set DB_ENGINE to postgresql and add TIMESTAMP_FORMAT according to your local Datetime format. Same for DATE_FORMAT even this has nothing to do with the database error.
