### ISSUE TITLE
MergeDelete was not found in MergeTablesToSync

### ISSUE THREAD

**Issue by hagabr** [sqlite-sync/SQLite-sync.com#4]
INFO DoSync(). Table dbo.MergeDelete was not found in MergeTablesToSync.

Always have this message in sync.log

Not sure if it's normal

**Comment by sqlite-sync** [comment]
MergeDelete should not be synced. It is local table created automatically on mobile. 
What client do you use (I mean Android, iOS or maybe HTML)?

**Comment by hagabr** [comment]
Ionic in Android

**Comment by sqlite-sync** [comment]
Fixed fd79474
